test click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -7,6 +7,10 @@ jobs:
   test:
     runs-on: ubuntu-latest
 
+    strategy:
+      matrix:
+        test_name: ["txxx", "pornq", "upornia", "100homemade", "chikiporn", "hclips", "hdzog", "hotmovs", "porn555", "pornforrelax", "pornl", "puporn", "shemalez", "shemaleztube", "thegay", "tubepornclassic", "vjav", "voyeurhit"]
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
@@ -37,20 +41,24 @@ jobs:
       - name: Start Xvfb
         run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
 
-      - name: Run tests and send results to Slack
+      - name: Run tests and save the results
         run: |
-          results=""
-          for test_name in txxx pornq upornia 100homemade chikiporn hclips hdzog hotmovs porn555 pornforrelax pornl puporn shemalez shemaleztube thegay tubepornclassic vjav voyeurhit; do
-            pytest -n auto > "test_$test_name.txt" || echo "Test failed" > "test_${test_name}_results.txt"
-      
-            test_result=$(<"test_${test_name}_results.txt")
-            if [ "$test_result" = "Test passed successfully" ]; then
-              results+="Click domains ($test_name):Test passed successfully\n"
-            else
-              results+="Click domains ($test_name):Test failed\n"
-            fi
-          done
-      
-          echo "$results" > all_test_results.txt
-      
-          curl -X POST -H 'Content-type: application/json' --data "{ \"text\": \"$results\", \"blocks\": [ { \"type\": \"section\", \"text\": { \"type\": \"mrkdwn\", \"text\": \"$results\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\" } } ] }" ${{ secrets.SLACK_WEBHOOK_URL }}
+          pytest -n auto > test_${{ matrix.test_name }}.txt || echo "Test failed" > test_${{ matrix.test_name }}_results.txt
+
+      - name: Use the test results
+        run: |
+          test_result=$(<test_${{ matrix.test_name }}_results.txt)
+          if [ "$test_result" = "Test passed successfully" ]; then
+            echo "TEST_STATUS=Click domains (${{ matrix.test_name }}):Test passed successfully" >> $GITHUB_ENV
+          else
+            echo "TEST_STATUS=Click domains (${{ matrix.test_name }}):Test failed" >> $GITHUB_ENV
+          fi
+
+      - name: Send test results to Slack
+        if: matrix.test_name == 'voyeurhit'
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+        run: |
+          TEST_STATUS=$(awk '/TEST_STATUS/ {print}' $GITHUB_ENV)
+          curl -X POST -H 'Content-type: application/json' --data "{ \"text\": \"$TEST_STATUS\", \"blocks\": [ { \"type\": \"section\", \"text\": { \"type\": \"mrkdwn\", \"text\": \"$TEST_STATUS\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\" } } ] }" $SLACK_WEBHOOK_URL
