Click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -61,26 +61,23 @@ jobs:
           Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
           sleep 3
 
-      - name: Run tests and save the results
-        run: |
-          results=()
-          for test_name in "${{ matrix.domain }}"; do
-            pytest -n auto > "test_${test_name}.txt" || results+=("Click domains ($test_name):Test failed ❌")
-            test_result=$(<"test_${test_name}_results.txt")
-            if [ "$test_result" = "Test passed successfully" ]; then
-              results+=("Click domains ($test_name):Test passed successfully ✅")
-            else
-              results+=("Click domains ($test_name):Test failed ❌")
-            fi
-          done
-      
-          # Результат
-          printf "%s\n" "${results[@]}" > all_test_results.txt
-
-      - name: Send test results to Slack
+      - name: Run tests
         if: always()
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+          ALL_TEST_RESULTS: |
+            results=""
+            for test_name in "${{ matrix.domain }}"; do
+              pytest -n auto > "test_${test_name}.txt" || echo "Click domains ($test_name):Test failed ❌" >> all_test_results.txt
+              test_result=$(<"test_${test_name}_results.txt")
+              if [ "$test_result" = "Test passed successfully" ]; then
+                results+="Click domains ($test_name):Test passed successfully ✅\\n"
+              else
+                results+="Click domains ($test_name):Test failed ❌\\n"
+              fi
+            done
+            echo "$results"
+
         run: |
-          echo "{\"text\": \"$(<all_test_results.txt | tr '\n' '\\n')\" }" > slack_payload.json
+          echo "{\"text\": \"$ALL_TEST_RESULTS\" }" > slack_payload.json
           curl -X POST -H 'Content-type: application/json' --data @slack_payload.json $SLACK_WEBHOOK_URL
