test click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -36,40 +36,40 @@ jobs:
       - name: Start Xvfb
         run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
 
-      - name: Run tests and save the results
+      - name: Run tests and save the results for test_txxx
         run: |
-          pytest > test_txxx.txt || echo "Test failed" > test_results.txt
+          pytest > test_txxx_results.txt || echo "Test failed" > test_txxx_results.txt
 
-      - name: Use the test results
+      - name: Use the test results for test_txxx
         run: |
-          test_result=$(<test_results.txt)
+          test_result=$(<test_txxx_results.txt)
           if [ "$test_result" = "Test passed successfully" ]; then
             echo "TEST_STATUS=Click domains (txxx):Test passed successfully" >> $GITHUB_ENV
           else
             echo "TEST_STATUS=Click domains (txxx):Test failed" >> $GITHUB_ENV
           fi
 
-      - name: Send test results to Slack
+      - name: Send test results for test_txxx to Slack
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
           SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
         run: |
           curl -X POST -H 'Content-type: application/json' --data "{ \"text\": \"$TEST_STATUS\", \"blocks\": [ { \"type\": \"section\", \"text\": { \"type\": \"mrkdwn\", \"text\": \"$TEST_STATUS\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\" } } ] }" $SLACK_WEBHOOK_URL
 
-      - name: Run tests and save the results
+      - name: Run tests and save the results for test_pornq
         run: |
-          pytest > test_pornq.txt || echo "Test failed" > test_results.txt
+          pytest > test_pornq_results.txt || echo "Test failed" > test_pornq_results.txt
 
-      - name: Use the test results
+      - name: Use the test results for test_pornq
         run: |
-          test_result=$(<test_results.txt)
+          test_result=$(<test_pornq_results.txt)
           if [ "$test_result" = "Test passed successfully" ]; then
             echo "TEST_STATUS=Click domains (pornq):Test passed successfully" >> $GITHUB_ENV
           else
             echo "TEST_STATUS=Click domains (pornq):Test failed" >> $GITHUB_ENV
           fi
 
-      - name: Send test results to Slack
+      - name: Send test results for test_pornq to Slack
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
           SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
