test click txxx

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -38,10 +38,7 @@ jobs:
 
       - name: Run tests and save the results
         run: |
-          pytest > test_txxx.txt
-
-      - name: Create the test results file
-        run: echo "Test failed" > test_txxx.txt
+          pytest > test_txxx.txt || echo "Test failed" > test_txxx.txt
 
       - name: Use the test results
         run: |
