Click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -64,15 +64,17 @@ jobs:
         run: |
           results=""
           for test_name in "${{ matrix.domain }}"; do
-            pytest -n auto > "test_${test_name}.txt" || echo "Click domains ($test_name):Test failed ❌" >> all_test_results.txt
+            pytest -n auto > "test_${test_name}.txt" || echo "Click domains ($test_name):Test failed ❌" > "test_${test_name}_results.txt"
             test_result=$(<"test_${test_name}_results.txt")
-            if [ "$test_result" = "Test passed successfully" ]; then
-              results+="Click domains ($test_name):Test passed successfully ✅\n"
+            if [ "$test_result" = "Click domains ($test_name):Test passed successfully ✅" ]; then
+              results+="$test_result\n"
             else
-              results+="Click domains ($test_name):Test failed ❌\n"
+              results+="$test_result\n"
             fi
           done
-          
+
+      - name: Combine results into one file
+        run: cat test_*_results.txt > all_test_results.txt
 
       - name: Send test results to Slack
         if: always()
