test click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -59,21 +59,21 @@ jobs:
       - name: Start Xvfb
         run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
 
-      - name: Run tests and save the results for each domain
+      - name: Run tests for each domain and save the results
         run: |
           for domain in ${{ matrix.domain }}; do
-            pytest -n auto -k "$domain" > test_$domain.txt || echo "Test failed" > test_$domain.txt
+            pytest -n auto -k "$domain" --json-report > test_$domain.json || echo "Test failed" > test_$domain.json
           done
 
       - name: Combine test results
-        run: cat test_*.txt > test_results.txt
+        run: cat test_*.json > test_results.json
 
       - name: Send test results to Slack
         if: always()
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
         run: |
-          test_result=$(<test_results.txt)
+          test_result=$(<test_results.json)
           if [ "$test_result" = "Test passed successfully" ]; then
             echo "TEST_STATUS=All tests passed successfully ✅" >> $GITHUB_ENV
           else
