Click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -1,16 +1,44 @@
+
 name: Automated tests
+
 on:
   push
+
 jobs:
   test:
     runs-on: ubuntu-latest
+
+    strategy:
+      matrix:
+        domain:
+          - txxx
+          - pornq
+          - upornia
+          - 100homemade
+          - chikiporn
+          - hclips
+          - hdzog
+          - hotmovs
+          - porn555
+          - pornforrelax
+          - pornl
+          - puporn
+          - shemalez
+          - shemaleztube
+          - thegay
+          - tubepornclassic
+          - vjav
+          - voyeurhit
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
+
       - name: Setup Python
         uses: actions/setup-python@v4
         with:
           python-version: "3.10"
+
       - name: Install dependencies
         run: |
           pip install pytest
@@ -19,27 +47,32 @@ jobs:
           pip install pytest-xdist
       - name: Install Chrome
         run: |
-          sudo apt-get update
-          sudo apt-get install google-chrome-stable
+          sudo apt-get update --fix-missing
+          sudo apt-get install -o Dpkg::Options::="--force-confnew" --reinstall google-chrome-stable
       - name: Set DISPLAY variable
         run: echo "DISPLAY=:99" >> $GITHUB_ENV
+
       - name: Install Xvfb
         run: sudo apt-get install xvfb
-      - name: Start Xvfb
-        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
-      - name: Run tests and send results to Slack
-        run: |
-          results=""
-          for test_name in txxx pornq upornia 100homemade chikiporn hclips hdzog hotmovs porn555 pornforrelax pornl puporn shemalez shemaleztube thegay tubepornclassic vjav voyeurhit; do
-            pytest -n 18 > "test_$test_name.txt" || echo "Test failed" > "test_${test_name}_results.txt"
-      
-            test_result=$(<"test_${test_name}_results.txt")
-            if [ "$test_result" = "Test passed successfully" ]; then
-              results+="Click domains ($test_name):Test passed successfully ✅\n"
-            else
-              results+="Click domains ($test_name):Test failed ❌\n"
-            fi
-          done
 
-          echo "$results" > all_test_results.txt
-          curl -X POST -H 'Content-type: application/json' --data "{ \"text\": \"$results\", \"blocks\": [ { \"type\": \"section\", \"text\": { \"type\": \"mrkdwn\", \"text\": \"$results\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\" } } ] }" ${{ secrets.SLACK_WEBHOOK_URL }}
+      - name: Start Xvfb
+        run: |
+          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
+          sleep 3
+      - name: Run tests and save the results
+        run: pytest -n auto > test_${{ matrix.domain }}.txt || echo "Test failed" > test_results.txt
+
+      - name: Use the test results
+        run: |
+          test_result=$(<test_${{ matrix.domain }}_results.txt)
+          if [ "$test_result" = "Test passed successfully" ]; then
+            echo "TEST_STATUS=Click domains (${{ matrix.domain }}):Test passed successfully ✅" >> $GITHUB_ENV
+          else
+            echo "TEST_STATUS=Click domains (${{ matrix.domain }}):Test failed ❌" >> $GITHUB_ENV
+          fi
+      - name: Send test results to Slack
+        if: always()
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+        run: |
+          curl -X POST -H 'Content-type: application/json' --data "{ \"text\": \"$TEST_STATUS\", \"blocks\": [ { \"type\": \"section\", \"text\": { \"type\": \"mrkdwn\", \"text\": \"$TEST_STATUS\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\" } } ] }" $SLACK_WEBHOOK_URL
