test click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -38,24 +38,16 @@ jobs:
 
       - name: Run tests and save the results
         run: |
-          pytest > test_results.txt || echo "Test failed" > test_results.txt
+          pytest test_txxx.py > test_results.txt || echo "Test failed" > test_results.txt
+          pytest test_vjav.py >> test_results.txt || echo "Test failed" > test_results.txt
 
-      - name: Use the test results for test_txxx
+      - name: Use the test results
         run: |
           test_result=$(<test_results.txt)
           if [ "$test_result" = "Test passed successfully" ]; then
-            echo "TEST_STATUS=Click domains (test_txxx): Test passed successfully" >> $GITHUB_ENV
+            echo "TEST_STATUS=Click domains: Test passed successfully" >> $GITHUB_ENV
           else
-            echo "TEST_STATUS=Click domains (test_txxx): Test failed" >> $GITHUB_ENV
-          fi
-
-      - name: Use the test results for test_vjav
-        run: |
-          test_result=$(<test_results.txt)
-          if [ "$test_result" = "Test passed successfully" ]; then
-            echo "TEST_STATUS=Click domains (test_vjav): Test passed successfully" >> $GITHUB_ENV
-          else
-            echo "TEST_STATUS=Click domains (test_vjav): Test failed" >> $GITHUB_ENV
+            echo "TEST_STATUS=Click domains: Test failed" >> $GITHUB_ENV
           fi
 
       - name: Send test results to Slack
