test click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -39,10 +39,20 @@ jobs:
       - name: Run tests and save the results
         run: |
           pytest > test_txxx.txt || echo "Test failed" > test_resultstxxx.txt
+          pytest > test_vjav.txt || echo "Test failed" > test_resultsvjav.txt
 
       - name: Use the test results
         run: |
           test_result=$(<test_resultstxxx.txt)
+          if [ "$test_result" = "Test passed successfully" ]; then
+            echo "TEST_STATUS=Click domains:Test passed successfully" >> $GITHUB_ENV
+          else
+            echo "TEST_STATUS=Click domains:Test failed" >> $GITHUB_ENV
+          fi
+
+      - name: Use the test results
+        run: |
+          test_result=$(<test_resultsvjav.txt)
           if [ "$test_result" = "Test passed successfully" ]; then
             echo "TEST_STATUS=Click domains:Test passed successfully" >> $GITHUB_ENV
           else
