Click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -61,18 +61,22 @@ jobs:
           Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
           sleep 3
 
-      - name: Use the test results
+      - name: Run tests and save the results
         run: |
-          test_result=$(<test_${{ matrix.domain }}_results.txt)
-          if [ "$test_result" = "Test passed successfully" ]; then
-            results+="Click domains (${{ matrix.domain }}):Test passed successfully ✅\n"
-          else
-            results+="Click domains (${{ matrix.domain }}):Test failed ❌\n"
-          fi
+          results=""
+          for test_name in "${{ matrix.domain }}"; do
+            pytest -n auto > "test_${test_name}.txt" || echo "Click domains ($test_name):Test failed ❌" >> all_test_results.txt
+            test_result=$(<"test_${test_name}_results.txt")
+            if [ "$test_result" = "Test passed successfully" ]; then
+              results+="Click domains ($test_name):Test passed successfully ✅\n"
+            else
+              results+="Click domains ($test_name):Test failed ❌\n"
+            fi
+          done
 
       - name: Send test results to Slack
         if: always()
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
         run: |
-          curl -X POST -H 'Content-type: application/json' --data "{ \"text\": \"$TEST_STATUS\", \"blocks\": [ { \"type\": \"section\", \"text\": { \"type\": \"mrkdwn\", \"text\": \"$TEST_STATUS\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\" } } ] }" $SLACK_WEBHOOK_URL
+          echo "$results" | curl -X POST -H 'Content-type: application/json' --data-binary @- $SLACK_WEBHOOK_URL
