test click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -43,19 +43,19 @@ jobs:
 
       - name: Run tests and save the results
         run: |
-          pytest -n auto > test_${{ matrix.test_name }}.txt || echo "Test failed" > test_${{ matrix.test_name }}_results.txt
+          pytest -n auto > test_${{ matrix.test_name[0] }}.txt || echo "Test failed" > test_${{ matrix.test_name[0] }}_results.txt
 
       - name: Use the test results
         run: |
-          test_result=$(<test_${{ matrix.test_name }}_results.txt)
+          test_result=$(<test_${{ matrix.test_name[0] }}_results.txt)
           if [ "$test_result" = "Test passed successfully" ]; then
-            echo "TEST_STATUS=Click domains (${{ matrix.test_name }}):Test passed successfully" >> $GITHUB_ENV
+            echo "TEST_STATUS=Click domains (${{ matrix.test_name[0] }}):Test passed successfully" >> $GITHUB_ENV
           else
-            echo "TEST_STATUS=Click domains (${{ matrix.test_name }}):Test failed" >> $GITHUB_ENV
+            echo "TEST_STATUS=Click domains (${{ matrix.test_name[0] }}):Test failed" >> $GITHUB_ENV
           fi
 
       - name: Send test results to Slack
-        if: matrix.test_name == 'voyeurhit'
+        if: matrix.test_name[0] == 'voyeurhit'
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
           SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
