test click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -6,7 +6,7 @@ on:
       deployment_target:
         description: Choose target
         required: true
-        default: second_test
+        default: test_txxx
         type: choice
         options:
           - test_txxx
@@ -54,21 +54,16 @@ jobs:
           Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
           sleep 3 
 
-      - name: first_test
-        if: "github.event.inputs.deployment_target == 'test_txxx'"
-        run: pytest test_txxx.py::test_domain --alluredir=allure-results
-
-      - name: second_test
-        if: "github.event.inputs.deployment_target == 'test_pornq'"
-        run: pytest test_pornq.py::test_domain --alluredir=allure-results
+      - name: Run tests and save the results
+        run: pytest -n auto > test_results.txt || echo "Test failed" > test_results.txt
 
       - name: Use the test results
         run: |
-          test_result=$(<test_${{ matrix.domain }}_results.txt)
+          test_result=$(<test_results.txt)
           if [ "$test_result" = "Test passed successfully" ]; then
-            echo "TEST_STATUS=Click domains (${{ matrix.domain }}):Test passed successfully ✅" >> $GITHUB_ENV
+            echo "TEST_STATUS=Click domains (${{ github.event.inputs.deployment_target }}):Test passed successfully ✅" >> $GITHUB_ENV
           else
-            echo "TEST_STATUS=Click domains (${{ matrix.domain }}):Test failed ❌" >> $GITHUB_ENV
+            echo "TEST_STATUS=Click domains (${{ github.event.inputs.deployment_target }}):Test failed ❌" >> $GITHUB_ENV
           fi
 
       - name: Send test results to Slack
