test first/second test

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -1,16 +1,8 @@
 name: Automated tests
 
 on:
-  workflow_dispatch:
-    inputs:
-      deployment_target:
-        description: Choose target
-        required: true
-        default: second_test
-        type: choice
-        options:
-          - first_test
-          - second_test
+  schedule:
+    - cron: '*/5 * * * *'
 
 jobs:
   test:
@@ -19,8 +11,24 @@ jobs:
     strategy:
       matrix:
         domain:
+          - txxx
+          - pornq
+          - upornia
           - 100homemade
           - chikiporn
+          - hclips
+          - hdzog
+          - hotmovs
+          - porn555
+          - pornforrelax
+          - pornl
+          - puporn
+          - shemalez
+          - shemaleztube
+          - thegay
+          - tubepornclassic
+          - vjav
+          - voyeurhit
 
     steps:
       - name: Checkout repository
@@ -52,13 +60,8 @@ jobs:
           Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
           sleep 3
 
-      - name: first_test
-        if: "github.event.inputs.deployment_target == 'first_test'"
-        run: pytest test_100homemade.py::test_domain
-
-      - name: second_test
-        if: "github.event.inputs.deployment_target == 'second_test'"
-        run: pytest test_chikiporn.py::test_domain
+      - name: Run tests and save the results
+        run: pytest -n auto > test_${{ matrix.domain }}.txt || echo "Test failed" > test_results.txt
 
       - name: Use the test results
         run: |
@@ -74,4 +77,3 @@ jobs:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
         run: |
           curl -X POST -H 'Content-type: application/json' --data "{ \"text\": \"$TEST_STATUS\", \"blocks\": [ { \"type\": \"section\", \"text\": { \"type\": \"mrkdwn\", \"text\": \"$TEST_STATUS\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\" } } ] }" $SLACK_WEBHOOK_URL
-
