test click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -118,15 +118,15 @@ jobs:
 
       - name: Run tests and save the results
         run: |
-          pytest > test_chiriporn.txt  || echo "Test failed" > test_results.txt
+          pytest > test_chikiporn.txt  || echo "Test failed" > test_results.txt
 
       - name: Use the test results
         run: |
-          test_result=$(<test_chiriporn_results.txt)
+          test_result=$(<test_chikiporn_results.txt)
           if [ "$test_result" = "Test passed successfully" ]; then
-            echo "TEST_STATUS=Click domains (chiriporn):Test passed successfully" >> $GITHUB_ENV
+            echo "TEST_STATUS=Click domains (chikiporn):Test passed successfully" >> $GITHUB_ENV
           else
-            echo "TEST_STATUS=Click domains (chiriporn):Test failed" >> $GITHUB_ENV
+            echo "TEST_STATUS=Click domains (chikiporn):Test failed" >> $GITHUB_ENV
           fi
 
       - name: Send test results to Slack
@@ -388,3 +388,10 @@ jobs:
           else
             echo "TEST_STATUS=Click domains (voyeurhit):Test failed" >> $GITHUB_ENV
           fi
+
+      - name: Send test results to Slack
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+        run: |
+          curl -X POST -H 'Content-type: application/json' --data "{ \"text\": \"$TEST_STATUS\", \"blocks\": [ { \"type\": \"section\", \"text\": { \"type\": \"mrkdwn\", \"text\": \"$TEST_STATUS\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\" } } ] }" $SLACK_WEBHOOK_URL
