Click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -61,12 +61,13 @@ jobs:
           Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
           sleep 3
 
-      - name: Run tests and save the results
+      - name: Run tests and send results to Slack
         run: |
           results=""
-          for test_name in "${{ matrix.domain }}"; do
-            pytest -n auto > "test_${test_name}.txt" || echo "Click domains ($test_name):Test failed ❌" >> all_test_results.txt
+          for test_name in txxx pornq upornia 100homemade chikiporn hclips hdzog hotmovs porn555 pornforrelax pornl puporn shemalez shemaleztube thegay tubepornclassic vjav voyeurhit; do
+            pytest -n 18 > "test_$test_name.txt" || echo "Test failed" > "test_${test_name}_results.txt"
             test_result=$(<"test_${test_name}_results.txt")
+
             if [ "$test_result" = "Test passed successfully" ]; then
               results+="Click domains ($test_name):Test passed successfully ✅\n"
             else
@@ -74,8 +75,5 @@ jobs:
             fi
           done
 
-          # Save results to a file
           echo "$results" > all_test_results.txt
-
-          # Send results to Slack
           curl -X POST -H 'Content-type: application/json' --data "{ \"text\": \"$results\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\" }" ${{ secrets.SLACK_WEBHOOK_URL }}
