Click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -65,20 +65,18 @@ jobs:
         if: always()
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-          ALL_TEST_RESULTS: |
-            results=""
-            for test_name in "${{ matrix.domain }}"; do
-              pytest -n auto > "test_${test_name}.txt" || echo "Click domains ($test_name):Test failed ❌" >> all_test_results.txt
-              test_result=$(<"test_${test_name}_results.txt")
-              if [ "$test_result" = "Test passed successfully" ]; then
-                results+="Click domains ($test_name):Test passed successfully ✅\\n"
-              else
-                results+="Click domains ($test_name):Test failed ❌\\n"
-              fi
-            done
-            echo "$results"
-
         run: |
-
-          echo '{"text": "'"$ALL_TEST_RESULTS"'"}' > slack_payload.json
+          results=""
+          for test_name in "${{ matrix.domain }}"; do
+            pytest -n auto > "test_${test_name}.txt" || echo "Click domains ($test_name):Test failed ❌"
+            test_result=$(<"test_${test_name}_results.txt")
+            if [ "$test_result" = "Test passed successfully" ]; then
+              results+="Click domains ($test_name):Test passed successfully ✅\n"
+            else
+              results+="Click domains ($test_name):Test failed ❌\n"
+            fi
+          done
+          
+          echo -e "$results" > all_test_results.txt
+          echo -e "{\"blocks\": [{\"type\": \"section\", \"text\": {\"type\": \"mrkdwn\", \"text\": \"$results\"}}]}" > slack_payload.json
           curl -X POST -H 'Content-type: application/json' --data @slack_payload.json $SLACK_WEBHOOK_URL
