Click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -62,22 +62,20 @@ jobs:
 
       - name: Run tests and save the results
         run: |
+          results=""
           for test_name in "${{ matrix.domain }}"; do
-            pytest -n auto > "test_${test_name}.txt" || echo "Test failed" > "test_${test_name}_results.txt"
+            pytest -n auto > "test_${test_name}.txt" || echo "Click domains ($test_name):Test failed ❌" >> all_test_results.txt
             test_result=$(<"test_${test_name}_results.txt")
             if [ "$test_result" = "Test passed successfully" ]; then
-              results+=("Click domains ($test_name):Test passed successfully ✅")
+              results+="Click domains ($test_name):Test passed successfully ✅\n"
             else
-              results+=("Click domains ($test_name):Test failed ❌")
+              results+="Click domains ($test_name):Test failed ❌\n"
             fi
           done
-
-          cat test_*_results.txt > all_test_results.txt
 
       - name: Send test results to Slack
         if: always()
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
         run: |
-          results_str=$(IFS=$'\n'; echo "${results[*]}")
-          curl -X POST -H 'Content-type: application/json' --data "{ \"text\": \"$results_str\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\" }" $SLACK_WEBHOOK_URL
+          echo "$results" | curl -X POST -H 'Content-type: application/json' --data-binary @- $SLACK_WEBHOOK_URL
