test click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -40,9 +40,11 @@ jobs:
       - name: Run tests and send results to Slack
         run: |
           results=""
-          for test_name in txxx upornia; do
-            test_result=$(pytest -n auto)
-            if [ $? -eq 0 ]; then
+          for test_name in txxx pornq upornia; do
+            pytest -n auto > "test_$test_name.txt" || echo "Test failed" > "test_${test_name}_results.txt"
+      
+            test_result=$(<"test_${test_name}_results.txt")
+            if [ "$test_result" = "Test passed successfully" ]; then
               results+="Click domains ($test_name):Test passed successfully\n"
             else
               results+="Click domains ($test_name):Test failed\n"
@@ -50,4 +52,4 @@ jobs:
           done
       
           curl -X POST -H 'Content-type: application/json' --data "{ \"text\": \"$results\", \"blocks\": [ { \"type\": \"section\", \"text\": { \"type\": \"mrkdwn\", \"text\": \"$results\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\" } } ] }" ${{ secrets.SLACK_WEBHOOK_URL }}
-                
+          
