test click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -43,18 +43,16 @@ jobs:
 
       - name: Run tests and save the results
         run: |
-          results=""
           for test_name in txxx pornq upornia 100homemade chikiporn hclips hdzog hotmovs porn555 pornforrelax pornl puporn shemalez shemaleztube thegay tubepornclassic vjav voyeurhit; do
-            pytest -k ${{ matrix.test_name }} > "test_${{ matrix.test_name }}.txt" || echo "Test failed" > "test_${{ matrix.test_name }}_results.txt"
-
-            test_result=$(<"test_${{ test_name }}_results.txt")
+            pytest -k $test_name > "test_${test_name}.txt" || echo "Test failed" > "test_${test_name}_results.txt"
+            test_result=$(<"test_${test_name}_results.txt")
             if [ "$test_result" = "Test passed successfully" ]; then
-              results+="Click domains (${{ test_name }}):Test passed successfully ✅\n"
+              echo "TEST_STATUS=Click domains ($test_name):Test passed successfully ✅" >> $GITHUB_ENV
             else
-              results+="Click domains (${{ test_name }}):Test failed ❌\n"
+              echo "TEST_STATUS=Click domains ($test_name):Test failed ❌" >> $GITHUB_ENV
             fi
           done
-
+          
           echo "$results" > all_test_results.txt
 
       - name: Send test results to Slack
