test click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -38,8 +38,7 @@ jobs:
 
       - name: Run tests and save the results
         run: |
-          pytest > test_txxx.txt || echo "Test failed" > test_results.txt
-          pytest > test_vjav.txt || echo "Test failed" > test_results.txt
+          pytest test_txxx.py > test_txxx.txt || echo "Test failed" > test_txxx_results.txt
 
       - name: Use the test results
         run: |
