test click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -40,6 +40,7 @@ jobs:
         run: |
           pytest > test_txxx.txt || echo "Test failed" > test_results.txt
           pytest > test_vjav.txt || echo "Test failed" > test_results.txt
+          pytest > test_pornq.txt || echo "Test failed" > test_results.txt
 
       - name: Use the test results
         run: |
