test click domains

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -60,11 +60,12 @@ jobs:
         run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
 
       - name: Run tests and save the results
-        run: pytest -n auto > test_${{ matrix.domain }}.txt || echo "Test failed" > test_results.txt
+        run: |
+          pytest -n auto > test_results.txt || echo "Test failed" > test_results.txt
 
       - name: Use the test results
         run: |
-          test_result=$(<test_${{ matrix.domain }}_results.txt)
+          test_result=$(<test_results.txt)
           if [ "$test_result" = "Test passed successfully" ]; then
             echo "TEST_STATUS=Click domains (${{ matrix.domain }}):Test passed successfully ✅" >> $GITHUB_ENV
           else
